### ISSUE TITLE
Percolator seg fault

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#390]
This command line leads to a segmentation fault:

/net/noble/vol1/home/noble/proj/crux/crux-toolkit/src/crux percolator --train-fdr 0.1 --test-fdr 0.1 --output-dir search --overwrite T search/tide-search.txt

It happens immediately after the modifications are created. The input file and log file are attached.

[percolator.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/1067495/percolator.log.txt)
[tide-search.txt](https://github.com/crux-toolkit/crux-toolkit/files/1067496/tide-search.txt)

**Comment by wsnoble** [comment]
Note that this seg fault happens during file conversion, so you can generate it just using make-pin:

crux make-pin search/tide-search.txt

Also, FYI, this file was created by the same search that leads to the threading bug in Issue #387 .

**Comment by kaipot** [comment]
This is due to a limitation in some of the legacy modification code, the `MODIFIED_AA_T` class is 16 bits, 5 bits are used to represent the amino acid leaving 11 bits to represent modifications. It looks like there are more than 11 different modifications in these search results, causing the crash. I will need to convert some more of the old modification code to use the new classes.

**Comment by wsnoble** [comment]
OK, seems like this is well worth doing then. Please let me know when you have a version I can test.

**Comment by kaipot** [comment]
[mods-update.txt](https://github.com/crux-toolkit/crux-toolkit/files/1073098/mods-update.txt)

This patch should fix the issue.

**Comment by wsnoble** [comment]
This patch fixes the issue in make-pin, but I still get a seg fault from the original Percolator command that I posted. It happens later in the run. Does it not happen for you?  I am running this on pyrrolysine.

I am attaching a new Percolator log file, this one generated using full verbosity.

[percolator.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/1075015/percolator.log.txt)

**Comment by kaipot** [comment]
My mistake, I had only tried it with make-pin, not Percolator. I'm working on fixing this, `MODIFIED_AA_T` is used in quite a few places.

**Comment by kaipot** [comment]
[mods-update2.txt](https://github.com/crux-toolkit/crux-toolkit/files/1096083/mods-update2.txt)

Here is an update, I discovered some bugs while making these changes so hopefully everything is working properly.

**Comment by wsnoble** [comment]
This patch does seem to fix the problem. All tests pass, and the code itself looks good. Please go ahead and check this in, then close this issue.
